name: flutter_value_notifier_stateful_widget
description: A reactive stateful widget for Flutter, backed by a `ValueNotifier` whose lifecycle is managed by the widget.
version: 1.0.1
repository: https://github.com/lukehutch/flutter_value_notifier_stateful_widget

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
